# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomefundo', models.CharField(max_length=80, null=True)),
                ('dtinicial', models.DateField(null=True)),
                ('dtfinal', models.DateField(null=True)),
                ('vlrmensalidade', models.FloatField(null=True)),
                ('diavencimento', models.CharField(max_length=2, null=True)),
                ('gestor', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('cnpj', models.CharField(max_length=18, null=True)),
                ('multa', models.FloatField(null=True)),
                ('juro', models.FloatField(null=True)),
            ],
        ),
    ]
