# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundo',
            name='id',
        ),
        migrations.AddField(
            model_name='fundo',
            name='id_empresa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fundo',
            name='id_fundo',
            field=models.IntegerField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
