# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0002_auto_20160823_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('ctrl_turma', models.IntegerField(primary_key=True, serialize=False)),
                ('id_turma', models.IntegerField(null=True)),
                ('nometurma', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('diavenc', models.CharField(max_length=2, null=True)),
                ('ativa', models.CharField(max_length=3)),
                ('dtformatura', models.DateField(null=True)),
                ('multa', models.FloatField(null=True)),
                ('juros', models.FloatField(null=True)),
                ('entrada', models.FloatField(null=True)),
                ('saida', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fundo',
            name='id_fundo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='turma',
            name='id_fundo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensalidades.Fundo'),
        ),
    ]
