# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0003_auto_20160823_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('controle', models.IntegerField(primary_key=True, serialize=False)),
                ('id_associado', models.IntegerField(null=True)),
                ('id_fundo', models.IntegerField(null=True)),
                ('nomeassociado', models.CharField(max_length=50, null=True)),
                ('logradouro', models.CharField(max_length=70, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('complemento', models.CharField(max_length=10, null=True)),
                ('bairro', models.CharField(max_length=70, null=True)),
                ('cidade', models.CharField(max_length=70, null=True)),
                ('uf', models.CharField(max_length=2, null=True)),
                ('cep', models.CharField(max_length=8, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('identidade', models.CharField(max_length=20, null=True)),
                ('fone1', models.CharField(max_length=13)),
                ('fone2', models.CharField(max_length=14)),
                ('id_turma', models.IntegerField(null=True)),
                ('ativo', models.CharField(max_length=3)),
                ('ctrl_perfil', models.IntegerField(null=True)),
                ('codbanco', models.CharField(max_length=20)),
                ('ctrl_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensalidades.Turma')),
            ],
        ),
    ]
