# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0004_associado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id_mens', models.IntegerField(primary_key=True, serialize=False)),
                ('id_fundo', models.IntegerField(null=True)),
                ('id_associado', models.IntegerField(null=True)),
                ('historico', models.CharField(max_length=60, null=True)),
                ('parcela', models.IntegerField(null=True)),
                ('numparcela', models.CharField(max_length=10)),
                ('valor', models.FloatField(null=True)),
                ('vlrextra', models.FloatField(null=True)),
                ('acresdesc', models.FloatField(null=True)),
                ('vlrliquido', models.FloatField(null=True)),
                ('jurosdescbanco', models.FloatField(null=True)),
                ('vencimento', models.DateField(null=True)),
                ('controlebanco', models.CharField(max_length=30, null=True)),
                ('pagamento', models.DateField(null=True)),
                ('formapagamento', models.CharField(max_length=30)),
                ('lote', models.CharField(max_length=20)),
                ('baixa', models.DateField(null=True)),
                ('lotebaixa', models.CharField(max_length=20, null=True)),
                ('codbarras', models.CharField(max_length=54, null=True)),
                ('linhadigitavel', models.CharField(max_length=54, null=True)),
                ('dtprocessamento', models.DateField(null=True)),
                ('id_contafd', models.IntegerField(null=True)),
                ('despesabanco', models.FloatField(null=True)),
                ('funcbaixa', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'associados',
                'verbose_name': 'associado',
            },
        ),
        migrations.AlterModelOptions(
            name='associado',
            options={'verbose_name': 'associado', 'verbose_name_plural': 'associados'},
        ),
        migrations.AlterModelOptions(
            name='fundo',
            options={'verbose_name': 'fundo', 'verbose_name_plural': 'fundos'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'turma', 'verbose_name_plural': 'turmas'},
        ),
        migrations.AlterField(
            model_name='associado',
            name='ativo',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ativa',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=3),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensalidades.Associado'),
        ),
    ]
