# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0005_auto_20160823_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associado',
            name='ctrl_turma',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='controle',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='dtformatura',
            new_name='data_formatura',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='diavenc',
            new_name='dia_venc',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='id_fundo',
            new_name='fundo',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='entrada',
            new_name='valor_juros',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='juros',
            new_name='valor_mensal',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='multa',
            new_name='valor_multa',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='diavencimento',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='id_fundo',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='juro',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='multa',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='vlrmensalidade',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='ctrl_turma',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='email',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='id_turma',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='saida',
        ),
        migrations.AddField(
            model_name='fundo',
            name='id',
            field=models.AutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Associado',
        ),
        migrations.DeleteModel(
            name='Mensalidade',
        ),
    ]
