# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0006_auto_20160825_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundo',
            old_name='dtfinal',
            new_name='data_final',
        ),
        migrations.RenameField(
            model_name='fundo',
            old_name='dtinicial',
            new_name='data_inicial',
        ),
        migrations.RenameField(
            model_name='fundo',
            old_name='nomefundo',
            new_name='nome_fundo',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='nometurma',
            new_name='nome_turma',
        ),
    ]
