# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 04:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensalidades', '0007_auto_20160825_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrodoc', models.CharField(max_length=10, null=True)),
                ('parcela', models.IntegerField(null=True)),
                ('valor', models.FloatField(null=True)),
                ('valor_extra', models.FloatField(null=True)),
                ('valor_acresdesc', models.FloatField(null=True)),
                ('valor_liquido', models.FloatField(null=True)),
                ('valor_jurdescbco', models.FloatField(null=True)),
                ('valor_despbco', models.FloatField(null=True)),
                ('data_vencimento', models.DateField(null=True)),
                ('data_pagamento', models.DateField(null=True)),
                ('data_proc', models.DateField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Associado')),
            ],
            options={
                'verbose_name': 'Financeiro',
                'verbose_name_plural': 'Financeiro',
            },
        ),
    ]
