# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0008_financeiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='valor_mensal',
        ),
    ]
