# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0009_remove_turma_valor_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='historico',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='data_proc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='nrodoc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='parcela',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor_acresdesc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor_despbco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor_extra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor_jurdescbco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor_liquido',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
