# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0010_auto_20161021_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiro',
            options={'verbose_name': 'financeiro', 'verbose_name_plural': 'financeiro'},
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='parcela',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
