# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160825_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mensalidades.Turma'),
        ),
    ]
