# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160825_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='nivel',
            field=models.IntegerField(default=0, verbose_name='nível'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='fone2',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='celular'),
        ),
    ]
