# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161008_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nivel',
            field=models.IntegerField(null=True, verbose_name='nível'),
        ),
    ]
