# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161008_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='complemento',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='complemento'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='fone1',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='telefone'),
        ),
    ]
